services:
  nginx:
    build: .                    # ← construye desde el Dockerfile
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - proxy-network
    volumes:
      - laravel_public:/var/www/html/public:ro
      - laravel_storage:/var/www/html/storage/app/public:ro

networks:
  proxy-network:
    name: proxy-network
    external: true