services:
  nginx:
    build: .
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - laravel_public:/var/www/laravel/public:ro
      - laravel_storage:/var/www/laravel/storage/app/public:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true

volumes:
  laravel_public:
    external: true
  laravel_storage:
    external: true